# Generated by Django 3.1.6 on 2021-04-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadproducto',
            name='ofertaProductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.ofertaproductor'),
        ),
        migrations.AlterField(
            model_name='cantidadproducto',
            name='pedidoProductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.pedidoproductor'),
        ),
        migrations.AlterField(
            model_name='cantidadproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.producto'),
        ),
        migrations.AlterField(
            model_name='cantidadproductocatalogo',
            name='canasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.canasta'),
        ),
        migrations.AlterField(
            model_name='cantidadproductocatalogo',
            name='pedidoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.pedidousuario'),
        ),
        migrations.AlterField(
            model_name='cantidadproductocatalogo',
            name='productoCatalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.productocatalogo'),
        ),
        migrations.AlterField(
            model_name='ofertaproductor',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.productor'),
        ),
        migrations.AlterField(
            model_name='pedidoproductor',
            name='ofertaProductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.ofertaproductor'),
        ),
        migrations.AlterField(
            model_name='pedidoproductor',
            name='pedidoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.pedidousuario'),
        ),
        migrations.AlterField(
            model_name='pedidousuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoCatalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.productocatalogo'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.usuario'),
        ),
    ]
